### ISSUE TITLE
PG actions are not captured with with larger trace

### ISSUE THREAD

**Issue by akshah123** [lightstep/otel-launcher-node#20]
**Describe the bug**
package is capturing postgres operations but instead of them being captured along with the larger trace they are captured by themselves.  This makes it difficult to correlate how each query is being made and in what context.

**To Reproduce**
I don't know if the problem is widespread or just in my setup. My configuration is pretty straight forward:

```javascript
const sdk = lightstep.configureOpenTelemetry({
      logLevel: 'debug',
      serviceName: 'serviceability'
    })

    await sdk.start()
```
**Expected behavior**
Pg spans are captured along with the entire trace so that in LIghtstep they show up under the actual request.

**Additional context**
I am using nodejs 12.14.1
OTel version: 0.11.0
PG plugin version: 0.10.0

**Comment by kayousterhout** [comment]
@akshah123 thanks for filing this issue - would you mind filing it on this repository: https://github.com/open-telemetry/opentelemetry-js-contrib/issues

We suspect this is an issue with the postgres plugin that's maintained there.

**Comment by akshah123** [comment]
@kayousterhout thanks.  Looks like someone else filed a similar bug here: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/213

Not sure if it was from your team but I am going to leave my comment there as well.

**Comment by obecny** [comment]
It was fixed in ~pg~ `KOA` plugin ver 0.11 and released ~with launcher ver. 0.12 2 days ago~  on 31st of Oct. -> https://www.npmjs.com/package/@opentelemetry/koa-instrumentation

**Comment by akshah123** [comment]
@obecny I have upgraded the plugins but am still seeing the same problem. I believe I have reproduced this issue with this repo here: https://github.com/akshah123/koa-test-app

**Comment by obecny** [comment]
@akshah123 getting
```
Pulling app-db (updater/base-postgis:4559)...
ERROR: pull access denied for updater/base-postgis, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by obecny** [comment]
@akshah123 nevermind, using different db

**Comment by obecny** [comment]
OK here is what is causing the problem. You are using knex to fetch data from sql. So between koa and pg you have knex. There is no plugin / instrumentation for knex available in otel yet. Without this there is no way to propagate context between koa and pg, so neither koa nor pg has a bug, it is a missing plugin for knex.

**Comment by obecny** [comment]
Created a feature request for new plugin / instrumentation https://github.com/open-telemetry/opentelemetry-js-contrib/issues/263

**Comment by obecny** [comment]
turn out that the problem itself is in knex and async hooks.
You have 2 solutions to fix that depends on the version of node you are using. If you are using latest you can override context manager

1. Use `AsyncLocalStorageContextManager`

```
const {
  lightstep,
} = require('lightstep-opentelemetry-launcher-node')

const { AsyncLocalStorageContextManager } = require('@opentelemetry/context-async-hooks');

module.exports = (async () => {
  const sdk = lightstep.configureOpenTelemetry({
    contextManager: new AsyncLocalStorageContextManager(),
    accessToken: 'YOUR TOKEN',
    logLevel: 'debug',
    serviceName: 'test-app'
  })
  await sdk.start()
})()

```

2. Use Promise based instead of async
```
...
      const movies = await knex('movies').select('*')
      ctx.body = {
        status: 'success',
        data: movies
      }
```
```
...
      const p = knex('movies').select('*')
      return p.then((movies)=> {
        ctx.body = {
          status: 'success',
          data: movies
        }
      })
```

**Comment by akshah123** [comment]
@obecny thank you so much for looking this.  I went ahead with your option #1 since we are using nodejs 14.

**Comment by akshah123** [comment]
going to close this issue as it is resolved for me.
